### ISSUE TITLE
Capped framerate is too slow

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#113]
I'm running this on Windows 10 64-bit, and disabling the "uncapped framerate" option makes the game run at about 20FPS, instead of Vanilla's 35. This happens with either setting of "Software rendering" in Doom, Heretic and Hexen.

Also, this is unrelated, but a feature suggestion: is it possible to add an option to disable autoaim in Heretic and Hexen? Because enabling the mouselook option makes autoaim feel redundant.

**Comment by JNechaevsky** [comment]
That's odd, everything seems to be okay on my side. What is refresh rate of your monitor?

The difference is - capped framerate is setting FPS to 35, while uncapped is setting to the monitor's actual refresh rate (60 Hz / 60 FPS in common cases), and never higher.

Software render is a bit different thing, it's mostly a SDL hack. It transfer all graphical calculations from video card (GPU) to CPU, but also eliminates interpolation between frames. Thus, when you have a capped framerate and software renderer, there will be a "rough" 35 fps, but still 35. In software + uncapped mode situation is a bit different, because interpolation is done in the code, but this also will require much more CPU power.

I was thinking about optional autoaim, but frankly, I'm afraid to do this by two reasons:

1. In Heretic and Hexen there a lot of tall areas, where monster can stand much higher than mouse look allows to see. This will enforce player to step backward for an ability to shoot monster. Unlike GZDoom, freelook working differently, and there is no way to have a proper 180° of up or down view.

2. In Doom it will have even worse aftermath - mechanics of invisible BFG spray is fully depending on autoaim. If I'll just disable autoaim, BFG will simply does not do any damage.

**Comment by hfc2x** [comment]
My monitor is 60 Hz.

Okay, so I ran the game through Steam, and the FPS counter says it's running at 35FPS. Sometimes the FPS drop to about 30 and then go back up. This tends to happen when mouselooking around. But after some tests, it's probably some configuration on my end, and not a bug in Russian Hexen.

About autoaiming, I see what you mean. This is just my personal opinion, but I never had a problem in older ZDoom versions (that could not look completely up or down) playing Hexen, and having autoaim enabled only seemed to get in the way of the monsters I wanted to shoot. I don't think it could work in Doom, since looking up and down breaks Doom 2 anyways. But it's fine either way in the end.

Are you planning on adding more bindable controls to the mouse buttons? Chocolate Heretic/Hexen have the option to bind "use inventory" to a mouse button, so I don't think it should be hard.

EDIT: The problem was that I was using "Software renderer" configuration. Disabling this made the game run at 35FPS.

**Comment by JNechaevsky** [comment]
Yeah, software rendering making framerate more rough because of missing frame interpolation, and thus, it feels like less than 35 fps. It's a mostly technical feature, which I'm keeping open for some compatibility.

I'm mostly "keeping" Heretic and Hexen, not "envolving" them because of lack of fanatical interest. But anyways, I still can add some binding from Chocolate version. Hexen already have an ability to bind all artifacts, but for keyboard only.

So, could you please provide a list of desired binding - what exactly should be bindable?

**Comment by hfc2x** [comment]
I'm actually mistaken. I checked Chocolate Doom, and it has exactly the same bindings as Russian Doom. I was misremembering, and I thought that "use inventory item" could be bound to the Mouse Wheel Click in Chocolate, because that's what I bind it to in most ports, and also in Strife: Veteran Edition.

But if you could add that, it would be very nice.
