### ISSUE TITLE
Options bug

### ISSUE THREAD

**Issue by hfc2x** [Russian-Doom/russian-doom#164]
First of all, thank you for Russian Heretic 4.0 lol. You're doing God's work by keeping Raven games alive.

That being said, I've been playing around with this release, and I found a couple bugs. The first one is in the Setup utility, inside the Display options, "Uncapped framerate" and "Show fps counter" are linked, so enabling/disabling any of them automatically does the same to the other. This happens in all Russian Heretic Setup, Russian Doom Setup and the unified Russian Setup utility.

The second bug I found is in the Gameplay Options of Russian Heretic in-game. The "show negative health" option shows "On" both when it's enabled and disabled. When it's disabled, the text renders in red, and it actually does disable it, but it's confusing.

Anyway, that's it for now.

**Comment by JNechaevsky** [comment]
Hello and thanks again! Yeah, sadly, Heretic and Hexen is a bit abandoned nowadays. I don't have a fanatical interest for them either, but trying to keep them alive at least in some good visual appearance. They worth and deserves it.

Setup executable starts to rot after I have moved everything rendering related into in-game menu. Negative health should also be easy to fix, and maybe even improved, because right now, if negative health is off, after enabling it player's health will still be `0`.

Anyways, I'll fix both issues, thanks!

**Comment by JNechaevsky** [comment]
@fabiangreffrath I have some thoughts about improving negative health, have to share.

For now, if player dies w/o `neghealth` enabled and after enabling `neghealth`, health value will still be `0` (because of this? https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_inter.c#L942).

But what if we'll always allow `< 0` for `player->health`, but with following logics:
* `neghealth` enabled: status bar allowed to draw health value `< 0`
* `neghealth` disabled: status bar NOT allowed to draw value `< 0` 

The only thing - I'm not exactly sure is it safe for demos / etc..

**Comment by fabiangreffrath** [comment]
Sure, we could change this so that it affects only rendering. I don't see anything demo-critical about this, because the player will still be dead and his health will still be `<= 0`.

However, I have seriously considered to remove this feature again. Not sure how much it adds to how dying "feels" in the game. And there are quite some places in the code affected by this - i.e. exactly by changing `healt == 0` checks to `health <= 0`, which is ugly...

**Comment by JNechaevsky** [comment]
@fabiangreffrath oh, I see. Really confusing, we have an `STlib_updatePercent` function, which leads to `STlib_updateNum`, which leads to `STlib_drawNum`, which finally decides what to draw: negative / zero / positive. Looks likes there is no way simple&fast way to add quick checking for neg. health in such approach.

**Comment by fabiangreffrath** [comment]
This is not that much of a problem. We could introduce another variable that is set equal to `plyr->health` and capped at `0` as the lower limit depending on whether "negative health" is enabled or not. We have done something very similar for the SG/SSG weapon availability widget.

**Comment by JNechaevsky** [comment]
That's an idea, thank you!
