### ISSUE TITLE
[Request] Proper WIDESCREEN rendering?

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#168]
@JNechaevsky , it seems that @fabiangreffrath has fixed widescreen for Crispy!

https://github.com/fabiangreffrath/crispy-doom/commit/c5a03d9754c1521ea0c78b45d34b1011c7a315e4

Will you please incorporate the fix to Russian Doom? Will look great on 16/9 modern displays!

**Comment by JNechaevsky** [comment]
I see... Sorry, I'm not sure I can handle it, despite of major idea is same (no bordered view), code is different between Crispy and RD.

**Comment by drfrag666** [comment]
@fabiangreffrath @bradharding
Really? RUDE codebase is way more different and closer to vanilla.
 What i did was overkill. To get one executable you need to change the SCREENWIDTH macro to a global variable with the same name initialized accordingly in i_video.c and then declare it as extern in i_video.h. You may want to pass a parameter from your laucher to set the variable.
 Then you could copy it to a local variable when used in core loops in r_draw.c so it's stored in a register.
 RUDE's implementation is loosely based on RD's. What i did was to some extent the inverse operation as you did, i changed width when needed  but you changed it everywhere with the macro and then undid the change.
 The key commit is fabian's "make sure the same number of horizontal pixels show the same game scene as in regular rendering mode" and then the related adjustments to projection and yslope[]. I put the original SCREENWIDTH there instead of HIRESWIDTH and you probably need ORIGWIDTH. I don't see why fabian didn't need the sliding flats fix. RUDE crashed due to not using MAXWIDTH for the tops array. For further reference now i support both modes (real wide and zoomed view) so you could check a recent commit of mine to see the differences.

**Comment by JNechaevsky** [comment]
I'm closing this now. It's implemented for Doom in https://github.com/JNechaevsky/russian-doom/commit/03ae3e838bcaa08cc227c200ab9ef54a54851651, and now Heretic is underway. 

Hopefully, it will happen in Hexen too, it's very outdated for now and even don't have a language hot-swapping.
