### ISSUE TITLE
[Feature Request] -pistolstart and -wandstart parameters (also dedicated reset level button?)

### ISSUE THREAD

**Issue by DwarsYT** [Russian-Doom/russian-doom#212]
This parameter was implemented in Doom Retro, and more recently Crispy Doom. The latter's implementation was done here: https://github.com/fabiangreffrath/crispy-doom/commit/2bdae1750348ba92abca6c9039a0fb7ee095b9a3

This would be a nice feature to have in this port, aside from a dedicated restart level button, also an option in Crispy (as well as PrBoom+ and even the Eternity Engine) and fixed in Heretic here: https://github.com/fabiangreffrath/crispy-doom/pull/640

**Comment by hfc2x** [comment]
That would be interesting but, shouldn't it have a more universal name? Probably something like `-inventoryreset` or something like that, so it can be used for both Doom and Heretic.

Of course, it would depend on what @JNechaevsky decides.

**Comment by JNechaevsky** [comment]
Hello!

Sure, I can add this into both Doom and Heretic, in Gameplay menu. The only question is - how should I properly name it in English? "Start every level with pistol"? 
![image](https://user-images.githubusercontent.com/21193394/94780269-dcf42200-03d0-11eb-8d61-aa8be32a5f42.png)

Dedicated restart level button also looks easy to implement. 

Another fun problem is - there is no proper translation for "pistol start" in Russian, we simply call absolutely similar to English "pistol start" and "wand start", but I'll handle it somehow. :)

**Comment by DwarsYT** [comment]
'Start every level with only pistol/wand' can work. Alternatives could include 'Reset inventory/arsenal after every level' for a more universal term. Parameters also work, so if both can be implemented, go for it!

Unrelated, but I noticed a typo in 'more agressive lost souls' - should be a**g**gressive.

**Comment by fabiangreffrath** [comment]
The de-facto term is "Pistol start", there is even a Doomwiki page for it.

**Comment by JNechaevsky** [comment]
@DwarsYT thanks, it fits well ([screenshot](https://user-images.githubusercontent.com/21193394/94819153-9837ad80-0407-11eb-95f7-1d825adf2cf8.png))! Typo is also fixed, looks likes it comes from Russian “агре́ссия” where only single “g” is used. I prefer to don't use any cmd line parameters, since RD is more Windows-oriented port, and I'm afraid not all Windows users are familiar with more or less powerful file explorers and/or batch files or command lines. Also, better keep all features in one place.

@fabiangreffrath, I know, I know. But I'm trying to give at least some brief descriptions. From another hand, "brightmaps" and "transparency" are single-word features.

**Comment by JNechaevsky** [comment]
Done for Heretic ([screenshot](https://user-images.githubusercontent.com/21193394/94827905-9f63b900-0411-11eb-8342-7ee70267537d.png)) :sparkles:

**Comment by JNechaevsky** [comment]
Dedicated restart/nexet level buttons are also available for Doom and Heretic, can be binded in Setup executable.

Are we done here? Or maybe something else? I'm currently lack of any new ideas and Strife is going really hard and slow. Just to don't wait another half of eternity, I can release a small point releases for all three games in the upcoming weekend.

**Comment by DwarsYT** [comment]
Should be it, regarding this issue.

One more thing I was going to consider writing up though, so I might as well do it here. I think CHAT would be a more adequate secret revealed sound for Heretic than the teleport sound. The teleport sound can easily get lost in the midst of actual teleporting, and CHAT is only heard in multiplayer or when changing specific settings.

**Comment by JNechaevsky** [comment]
All done! `telept` sound replaced with `chat` now.

**Comment by JNechaevsky** [comment]
Just want to say - I've never played before with pistol start, but now just finished HoE with this feature. That's something both interesting and habit-breaking. Most of tactics, formed for years (even decades!) are mostly non effective, but knowing routes and weapons/ammo placement helps a lot for sure. Probably, beating the game this way with 100% K/I/S and flipped levels will be even more challenging, worth to try someday.

**Comment by JNechaevsky** [comment]
Guys, I apologize for release delay, but I want to implement an in-game key bindings menu at last. For now it's mostly working, but I need to improve it's logics and code (there is a terrible bunch of `if key == ...` conditions, which defines where to print character like "A / B / C" and where to print key name like "Caps Lock / BackSpace"). Here's a first non-nicely aligned prototype:

![image](https://user-images.githubusercontent.com/21193394/95507696-72d41200-09ba-11eb-8859-6d98f354a0b9.png)

**Comment by JNechaevsky** [comment]
Some good and bad news.

Good:
* Keyboard bindings menu is working just fine. I've implemented all necessary logics:
  * Binding can be cleared by `DEL` key.
  * Binding same key to current item will clear binding.
  * Pages can be scrolled by `PgUp`/`PgDn` keys.

Bad:
* The code is **extremely huge** and linear. No, this will not affect game / OS performance, but in terms of programming this is something really not smart. 
* There is no checking if key was binded already.
* There is no dual/triple binding ability (not supported by Chocolate Doom code).
* Mouse key bindings menu was planned and implemented, but I have some problems with catching mouse key events. Only left and right buttons are can be assigned correctly, while middle, wheel and side buttons are not. Not sure what to do, probably I'll just remove this menu until it will not work 100% fine.
* No idea, will it all work in Heretic/Hexen menu system, since I'm using mostly vanilla code of Doom menu system.

Here's a quick example of how it looks: https://youtu.be/Odufl52-sNk

**Comment by hfc2x** [comment]
Is it possible to leave the controls binding menu for later for the Raven games? Or you're concerned about consistency among all games?

If you want to implement that menu in Heretic and Hexen before releasing an update, I think it's alright to delay it. It could also give you time to clean up the code a bit, if you feel like it's not up to par yet.

**Comment by hfc2x** [comment]
About mouse buttons, I think it could help to take a look at [Eternity](https://github.com/team-eternity/eternity)'s [i_input.cpp](https://github.com/team-eternity/eternity/blob/master/source/sdl/i_input.cpp), since it uses a modified version of the input event handling of Choco Doom and it does catch Mouse3 clicks. I have no idea how easy or hard would it be to backport the mouse event handler, since I know really little about C and C++ lol.
