### ISSUE TITLE
Jaguar Doom: W_GetNumForName: ENDoom not found

### ISSUE THREAD

**Issue by cubebert-github** [Russian-Doom/russian-doom#214]
I'm using the stable version of Russian Doom 4.5 and I have the settings for showing the ENDOOM screen on. Every time I launch Ultimate Doom with the -jaguar command line argument and quit the game, a message shows up telling me that an ENDOOM lump isn't available. I've looked at doom-jaguar.wad and there isn't an ENDOOM lump, but is there any reason Russian Doom doesn't use Doom's regular ENDOOM as a fallback instead?

**Comment by JNechaevsky** [comment]
Hello @cubebert-github and thanks for report!

Yep, there is no `ENDOOM` lump in doom-jaguar.wad. Since doom-jaguar.wad is completely standalone (i.e. does not require any existing IWADs) (a), and there is no `ENDOOM` appearing in vanilla Jaguar Doom (b), I think I just can disable showing for RD Jaguar.
