### ISSUE TITLE
Russian Doom 4.5: Bug reports & suggestions

### ISSUE THREAD

**Issue by cubebert-github** [Russian-Doom/russian-doom#215]
I wanted to do both a bug report and ask for a couple of suggestion for the stable version of Russian Doom 4.5 since I don't know if they will be resolved in the upcoming release.

1. There seems to be an issue regarding widescreen assets not being loaded on Plutonia and TNT, at least on my launcher. The TITLEPIC, INTERPIC, BOSSBACK, and intermission text will use Doom 2's instead of the respective games. I'm using ZDL 3.2.2.2 and the Id Anthology releases of these games, which have different Iwads than the retail versions. Is there something that I'm missing when I'm launching these games or is that just an error?

![image](https://i.imgur.com/Ftp1zTk.png)

2. Normally with the "Extra player faces on the hud" setting turned off, the god mode mugshot will stay static even while firing weapons for a while. However, on wads that use custom status bar mugshots such as Freedoom, Batman Doom, or STRAIN, the mugshot will go to the pain state like in Vanilla Doom.

3. On FreeDoom, the options for "Rendering Options" have text that overlaps, particularly on the first two options.

![image](https://i.imgur.com/ubXSF2L.png)

4. Is it possible to have an option to disable the key flashing for trying to open locked doors? I know some players would like this, and I like the implementation, but I'm usually a vanilla player and that feature is just a bit jarring to have since that's from the Playstation port.

5. On some wads such as Doom 64 for Doom II, there are widescreen status bars that don't show in Russian Doom but do in other ports such as Crispy Doom. Is there a way to have it so that those status bars can show up whenever possible?

It's a fairly long list, but since I'm not a frequent GitHub user, I wanted to write it down in a singular post without clogging up the issue tracker. I heavily appreciate your hard work and I can say for sure that Russian Doom is my main source port for vanilla and limit-removing wads! Let me know if you are welcome to this sort of report since I could do more of them for future releases.

**Comment by JNechaevsky** [comment]
Hello @cubebert-github, and thanks for your time!

Sadly, for now I'm too exhausted by RD project, and can't do anything in next couple of weeks, just need some rest. But anyways:

1) Got the same. Looks likes, ZDL is invoking running by some kind of unsupported, not only wide screen assets wrong, even map names are from Doom II. Not sure what to do, I need to see what's command ZDL is using to start the game, but there is no such option. Using common `russian-doom.exe -iwad TNT.WAD` should work just fine.

2) There is a maze of conditions in the code, I will need to dig it.

3) That's the problem of different font width in menus. Probably I'll just use common Doom font for them, this should fix such cases.

4) Not sure it is a good idea to add a micro-switch for this, but you may wish to try `-vanilla` command line parameter, which will emulate vanilla game behavior in many aspects.

5) I haven't done anything to support widescreen status bars for now, so for now, they always will be messy. :( Guess I should do something about it.

And thank you for kind again! Sorry, I can't exactly say when I'll back to work on RD, but this is not the end for sure. :)

**Comment by cubebert-github** [comment]
No worries, I can understand needing some resting time after a project. Feel free to take however long you need to rest up.

**Comment by JNechaevsky** [comment]
Figured out case №1! ZDL is inwoking commands using slash (`/`), while port is properly understanding only backslashes (`\`) in paths:

![image](https://user-images.githubusercontent.com/21193394/97345860-ad371d80-189b-11eb-8401-107c66d1f1c8.png)

Guess I have to replace slashes to backslashes on fly somehow.

**Comment by hfc2x** [comment]
@JNechaevsky I'm pretty sure Choco already fixed this one. Gonna check and submit a pull request if I find the solution.

**Comment by JNechaevsky** [comment]
Starting game via ZDL now fixed (as well as using slashes instead of backslashes in given paths).

@cubebert-github, @hfc2x, looks likes everything done for now for 4.6. Or there will be additional suggestions?

**Comment by hfc2x** [comment]
Did you test if your mouse was working properly now? Also, is the Heretic and Hexen inventory system saving its position like Strife? I remember that was a feature you wanted to implement.

**Comment by hfc2x** [comment]
Also, I was doing some changes to the menu code in my fork, and I thought I introduced a bug, but turns out the bug is present in the current codebase.

Loading a game saved at skill 6 in Heretic while using the `-vanilla` parameter causes the player to be unable to pick up items.

**Comment by JNechaevsky** [comment]
> Did you test if your mouse was working properly now? Also, is the Heretic and Hexen inventory system saving its position like Strife? I remember that was a feature you wanted to implement.

Well, mouse bindings working fine, except some mystery with binding next/previous weapon by side buttons. Probably something goes wrong with menu event catching, but still no idea what exactly. Another problem is - binding code _(read: project's author)_ is not smart enough to prevent double bindings, so player literally can bind everything to one key, but for very first implementation of in-game bindings, I think this is okay.

Heretic, Hexen and Strife inventory position is not fixed (https://github.com/JNechaevsky/russian-doom/issues/70), not sure what to do.

> Also, I was doing some changes to the menu code in my fork, and I thought I introduced a bug, but turns out the bug is present in the current codebase.

What exactly you are trying to do?

> Loading a game saved at skill 6 in Heretic while using the -vanilla parameter causes the player to be unable to pick up items.

Hm, that's odd, I can't reproduce it. Could you please provide step-by-step instruction?

**Comment by hfc2x** [comment]
> Hm, that's odd, I can't reproduce it. Could you please provide step-by-step instruction?

I cloned the repository with Git, and compiled the executables. Launched Russian Heretic in skill 6, saved the game, closed. Then, relaunched the game, this time with `-vanilla` parameter, and loaded the saved game. Now, I can't pick up items anymore.

This only happens in Heretic. All other games work properly by doing this.

**Comment by cubebert-github** [comment]
Everything seems to look good for a 4.6 release apart from the mentioned Heretic bug. Does skill 6 affect item pickups in anyway? I'll test out Russian Doom and Hexen to see if the bug also occurs there.

**Comment by hfc2x** [comment]
It doesn't happen in any of the other games. Just Heretic.

**Comment by cubebert-github** [comment]
I've checked and you're right, the bug doesn't happen on Doom or Hexen. However, with Russian Heretic 4.2, I seem to be able to launch the game at skill 6, save and close the game, re-launch the game with the "-vanilla" parameter, and pick up items from the save (In my case, they were wand crystals, so maybe it was a different item you were talking about?) Was the bug introduced in one of the commits after the release of RHer 4.2?

**Comment by JNechaevsky** [comment]
Guys, I'm still not lucky with reproducing. :/ Could you please provide a savegame  file?

**Comment by cubebert-github** [comment]
I've made two save files using the latest stable version of Russian Heretic; both of them are on skill 6, but the second file was saved with the -vanilla parameter. At least in my case, both files let you pick up items in the same level. @hfc2x, you've mentioned that you cloned the repository and got the bug, do you know if the bug occurs on RHer 4.2?

[savegames.zip](https://github.com/JNechaevsky/russian-doom/files/5726586/savegames.zip)

**Comment by JNechaevsky** [comment]
Caught! @cubebert-github @hfc2x am I right, that you are using Win-32 version? For some reason, this is not happening in Win-64 build. :open_mouth:

**Comment by cubebert-github** [comment]
I'm using the Win64 build. Right now, I found a couple of bugs in Russian Doom 4.6, so I'll test them out in 4.6.1 and see if they need to be reported or not.

**Comment by cubebert-github** [comment]
Okay, so I've finished testing out 4.6.1 and made my report.

1. There's a bug regarding item pickups where either dying or loading a save on the same level can cause items to no longer be obtainable.

2. DSBOSSIT and DSBOSDTH don't seem to play their respective sounds.

3. If the M_DOOM graphic covers the status bar, whatever was in the status bar stays in it permanently until you increase the screen size. I've included a video that shows it on Hell Revealed 2, which has a large M_DOOM graphic lump. I apologize for the horrendous video quality, but it should demonstrate what I am referring to.

That's about it for the bug report. Since we're at 4.6.1, should I close the issue and delegate this to a different one or should I keep this one open?

https://user-images.githubusercontent.com/24487663/103569488-3a8a8580-4e7c-11eb-9937-97e717e35911.mp4

**Comment by JNechaevsky** [comment]
Thanks for checking!

> 1. There's a bug regarding item pickups where either dying or loading a save on the same level can cause items to no longer be obtainable.

Is it still in Heretic, or now happens in Doom? :fearful:

> 2. DSBOSSIT and DSBOSDTH don't seem to play their respective sounds.

That's odd, it must be fixed already. Clarify please, is it happening on clean Doom II, or in some kind of mod? And which amount of SFX channels do you have in Sound Options menu?

> 3. If the M_DOOM graphic covers the status bar,

Oh, this one is clear enough. It's not really a bug, but a vanilla behavior, I'll briefly explain: in vanilla Doom, status bar GFX is not redrawing every single tic. Instead, only digits and their backgrounds are redrawing. Back in 1993 it was a smart idea for performance, since CPUs was not that fast like nowadays. Pretty much same was done in Heretic and Hexen, and as a result of this, in case of some kind of menu GFX is places over the status bar background, it will remain until full status bar refresh, that's why mod authors should always keep in mind to not overlay any menu-related GFX over the stbar.

Anyways, it can be easily fixed: stbar can be constantly redrawn while in Main, Episode and Skill menus, where some custom GFX can be potentially used: https://github.com/JNechaevsky/russian-doom/commit/968b7844d8cb8623683024345187c503b66ed806 (@fabiangreffrath, have a look please, same is happening in Crispy).

Please keep this issue open until we figure out 1 and 2 cases.

**Comment by cubebert-github** [comment]
1. It doesn't occur in Heretic, at least on the Win64 build of RHer 4.3. The bug only happens if you save and reload the same file. Quitting Russian Doom and loading from the title screen before the demos play seems to fix it.

2. Using stock Doom 2 and testing out MAP30, I've tried changing the sound channels to see if it fixes it. Apparently, if the sound channel limit is set to 64 or a similarly high number, the sounds for both the Icon of Sin and the spawn cube appearing will be silent. Occasionally, they won't make sounds if I put them on 60 or 56, but most of the time, they'll make sounds. It might be unrelated, but while I was using IDCLEV to restart MAP30 about 6-7 times (I think that's the number), I got an error message and a fatal crash.

![2021-01-05_135554](https://user-images.githubusercontent.com/24487663/103704921-0045e480-4f5f-11eb-9ee9-b91d6fcaac74.png)

**Comment by JNechaevsky** [comment]
@cubebert-github thank you again. Second issue seems to be fixed now (https://github.com/JNechaevsky/russian-doom/commit/b124df4c8ec0eb5762990def2d90163a621cf44c). If I'm getting things right, without `-1` sound was trying to play in 65th channel which is not existing, and most probably, something was going crazy by reading garbage from the memory.

As about first one, I need some additional clarification:
* Is it happening randomly, or is there a direct way to reproduce it?
* Is it happening before reproducing bug №2?
* Are you sure you have unpacked all files (executables, dlls, subfolders) from 4.6.1 release archive?

I've tried to make a stress-test by saving/loading on MAP30 and MAP15 of Sunder _(not really playable because of Boom specifics, but ultimately handy for performance testing)_ - no luck, pickups as well as blockmapping working fine. You can also reload current level directly, if you bind a key ([screenshot](https://user-images.githubusercontent.com/21193394/103748758-a522f900-5015-11eb-8177-caaa05ea814b.png)).

P.S. May I add you to the acknowledgments section? If so, how should I write your name/nickname?

**Comment by cubebert-github** [comment]
The bug seems to trigger randomly, but here are the steps to try to reproduce it. Sometimes it works, but other times it doesn't; I have no idea what affects the chances of it happening, but it should occur on the latest version of Russian Doom. This happened to me while I was playing Rowdy Rudy's Revenge, an addon for Doom 2, and while I was testing out the steps for Doom 64 for Doom 2 and stock Doom 2.

1. Start a new game
2. Wait for a minute or two
3. Save the game
4. Load the save (You might have to take damage before loading, but I'm not sure.)

Alternatively, you can wait for the demos to play and load the affected save file. Either way, it should trigger the bug and persist until you restart a new game or quit and load the save before the demos play. The bug doesn't seem to be related to the second bug that you've fixed, and I do believe that I have extracted the 4.6.1 release archive into its' own folder (My directory for the folder is C:\Games\PC\Doom\Source Ports and Mods\russian-doom-4.6.1-win64).

I hate to introduce another bug into the report, but I thought I point out that some of the ASCII art in the ENDOOM lump seem to conflict with the Cyrillic characters. For comparison, the top image is how Russian Doom renders Doom 64 For Doom 2's ENDOOM and the bottom is how Chocolate Doom renders it.

![2021-01-06_130804](https://user-images.githubusercontent.com/24487663/103821183-8a0ab600-5022-11eb-9af8-7badca40d7d6.png)

![2021-01-06_130857](https://user-images.githubusercontent.com/24487663/103821191-8d9e3d00-5022-11eb-9816-22b7471343a8.png)

Also about the acknowledgements section, feel free to add my user handle to the list.

**Comment by JNechaevsky** [comment]
Finished half of Doom 2 and half of Rowdy Rudy's Revenge with periodical save/load, as well as tried to make some stress-test with saving-loading-changing maps. No luck, pickups are always working fine. :/ No sure what to do...

A case with ENDOOM screen is not really a bug. I need to have both English and Russian characters for this emulated text mode (it is also used for rendering Setup), but I'm limited to 256 characters table. To make Russian chars available, I have changed some of pseudo-graphic symbols to Russian chars, this approach is pretty much same as it was done back in DOS era. :)

![ascii](https://user-images.githubusercontent.com/21193394/103938287-114b4d00-513b-11eb-9dcd-fdd937c1c98f.gif)

In theory, I could use both font tables and use US-only if game language is set to English. But the problem is - I don't see any simple ways to indicate "textscreen" library which font to use depending on `english_language` game variable.

Could you please take a try this build? I've made some small changes, maybe it will help? There is executable only, just unpack it into released 4.6.1 folder.
[russian-doom-4.6.1-1.zip](https://github.com/JNechaevsky/russian-doom/files/5783732/russian-doom-4.6.1-1.zip)

**Comment by cubebert-github** [comment]
I've tried both the build you've provided and the 32-bit build on the first two levels of Doom 2, and I still come across that bug. I did discover how to more accurately trigger the bug though. If you make a save file, wait for 70 seconds, and load the save file, the bug will occur. Pistol starting or manually restarting the level seems to fix the current game session though. My operating system is Windows 7 64-bit, so maybe that's the reason why you're not getting the bug?

I guess for the ENDOOM lump, I would say for now, put it aside and figure out how to separate the font tables for different languages at a later version.

**Comment by hfc2x** [comment]
Hey, sorry for disappearing. Been busy irl.

I've been unable to build the 64-bit version of Russian Heretic to test, but yes, the bug I encountered was in the 32-bit version. I'm running it on Windows 10 64-bit, by the way.

**Comment by JNechaevsky** [comment]
Sorry for being quite last days, I've got a Covid. Well, physically I'm totally okay, but lost senses of taste and smell. This demoralizes a bit, so I don't have a will to work with code for now. This sucks. :/

@cubebert-github, I've tried to run both x32 and x64 build on virtual Windows 7 x64 - still no luck with reproducing. My only suspicion left is - this can be one of gameplay features. Could you please share your `russian-doom.ini`?

@hfc2x, this seems to be a mystery with x32 build and `-vanilla` game loading bug. Vanilla mode is not preserved in saved game in any way, so I have no idea what can cause this. Maybe I need to try to disable step-by-step `vanillaparm` condition in the code and try figure out will it help... So what's the problem with building x64 version? Are you using MSYS?

**Comment by cubebert-github** [comment]
I'm sorry to hear about that. Hopefully, you'll be able to recover from this at some point. Here's my config file for Russian Doom; feel free to take a few days off if you need to.

[russian-doom-config.zip](https://github.com/JNechaevsky/russian-doom/files/5817326/russian-doom-config.zip)

**Comment by fabiangreffrath** [comment]
Ih my God, that's shocking news! I hope you are rather well and only suffer a mild course of sickness. Keep up the faith! 🤞

**Comment by JNechaevsky** [comment]
Dear Fabian, thank you very much for kind words! 

I think I'm getting well, at last I'm able to feel the taste and smell. Not completely, it's about 60% of how it was before covid, but frankly, it's a great happiness! My wife also was affected, obliviously because of me, but was having a high temperature for about first three day. Now she's also fine, but lost taste and smell.

I've read some texts from the people who also suffered covid - yeah, loosing taste/smell is happening in 90% cases, but people are different, and someone recovering in about two weeks, while for someone it takes few months for nominal recover. No info about when senses will recover completely, though.

So yeah, there is nothing terrible in fact, at least for our ages. But have say, mask and gloves are not panacea. I've also wasn't calling for doctor, all this time I was working normally - it wasn't possible for me to get isolated, I needed to be at work and luckily 90% of time I'm sitting alone, so everyone is fine.

Also, I haven't done anything to get well sooner, no idea was it possible at all, but I was drinking a lot of water, about 3 liters per day. Not sure if it helps, but anyway, it's a good practice for overall condition.

**Comment by fabiangreffrath** [comment]
Good to know you are feeling better already! I have also heard report of people who recover well and get their senses back after quite some time. Just keep up the good faith, you've got the worst part past yourself already. All the best to you and your wife. 👋

**Comment by JNechaevsky** [comment]
Looks likes everything is done here. Heretic's problem with non-pickupable items will be solved in upcoming RH 5.0 version.

As about same strange case in Doom... Honestly, still no idea what could it was. My only suspicion about something went wrong with memory used by RD (i.e., it's a RD problem, not a PC problem), but things changed a lot, so I can only hope that it will gone in upcoming RD 5.0 version.
