### ISSUE TITLE
Account Z coordinate for sound distance

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#220]
Should be this @ `S_AdjustSoundParams`:
```
    fixed_t        approx_dist;
    fixed_t        adx;
    fixed_t        ady;
+++ fixed_t        adz;
    angle_t        angle;

    // calculate the distance to sound origin
    //  and clip it if necessary
    adx = abs(listener->x - source->x);
    ady = abs(listener->y - source->y);
+++ adz = abs(listener->z - source->z);

    // From _GG1_ p.428. Appox. eucledian distance fast.
--- approx_dist = adx + ady - ((adx < ady ? adx : ady)>>1);
+++ approx_dist = adx + ady + adz - ((adx < ady ? adx : ady)>>1);
```

But how to name this feature shortly in both languages?

**Comment by JNechaevsky** [comment]
Map for quick testing: [snddist.zip](https://github.com/JNechaevsky/russian-doom/files/5633495/snddist.zip)

If player hits switch, a lift with demons goes down to -2048 map units. The more demons are lowering, the more sound get quieter. But platform sound is still hearable pretty well, duh.

@fabiangreffrath, @bradharding, worth to suggest and/or discuss?

**Comment by fabiangreffrath** [comment]
Neat idea, but I have a few doubts:

1. People are *very* sensitive about changes to audible perception - perhaps more than visible changes, because they are more subtle. And changing monster sounds this way will very much alter the spatial recognition of a map. I agree that it adds to realism, but this is often not what people are looking for in a game like Doom, which is mostly driven by muscle memory and nostalgia.

_I have gone similar ways before several times with Crispy (remember e.g. flattening out of fake shadows) and this looks like one of the changes that people request you to revert immediately after the next release._ 😉 

2. The formula for `approx_dist` looks like a linear approximation of the Pythagorean theorem `d = sqrt(x^2 + y^2)` in 2D. I doubt this is extended to 3D by merely slapping an `adz` in there.

3. Since distances in 3D are always longer (i.e. at least exactly as long) as in the 2D projection, the only variation this will bring is that on average sounds will be quieter than before. It's impossible for a sound to become louder and thus raise awareness with this change.

**Comment by JNechaevsky** [comment]
Sure do, I always remember this thing about sound! From another hand, this feels... "Correct" or "proper", so it definitely have a chance to be turned on by default. There are already lots of things, that's not similar to vanilla, but most of them are visual of course. I'm not trying to have a 100% vanilla experience "from the box" after all.

Well, my knowledge about geometry is same to mathematics, which are something about  in middle school level _(I am a humanitarian who prefer to smell the scent of roses! :smiley:)._ But I believe we don't need an 100% perfect accuracy counting for sound, it is not a visible thing, and probably even with ear for music it is never possible to say how far monster is.

You absolutely right about reducing volume, but this _"should"_ be correct. Have a look, imagine that player is a green circle, and monster who standing below is a red circle. Z and X axis are same to Doom. In vanilla we always have a `A` line, by adding vertical distance we have a `B` line, which is longer, and which is meaning that distance is more far and sound should be quieter.

![image](https://user-images.githubusercontent.com/21193394/101130345-59df8a00-3614-11eb-8af5-d6457567a237.png)

This is of course is just a theory, which never fits into real game feeling. Good thing that in testing map it feels correct, but real walkthrough experience is still not tested. I think TNT is an perfect example, because there were no tall _(wide? long? what's that word?)_ heights in Doom 1, not much in Doom 2 and Plutonia, but really notable in some levels of TNT, like Deepest Reaches.

Finally, real headache will be attaching `Z` coord to the `soundorg` of ceilings (doors, crashers) and floors (lifts, platforms), because they simply must have it to make this feature 100% correct. 🤯 I think ceiling `soundorg` `Z` should always have a `ceilingheight` and floors `floorheigh` respectively.
