### ISSUE TITLE
Incorrect lighting in Doom and Heretic

### ISSUE THREAD

**Issue by Mushman** [Russian-Doom/russian-doom#245]
Using Russian Doom 4.7.1 and Russian Heretic 4.3, the lighting in both games is brighter than it should be. This issues does not affect Russian Hexen 4.1. The lighting settings each screenshot use are `Video Renderer: Hardware (GPU)`, `Standard Gamma Correction Off` and `Level Brightness 0`. Even when changing these values, there doesn't appear to be a combination that appears close to the visuals in other ports. Changing the `Video Renderer` setting has no visual effect.

I've included a simple HTML gallery viewer to make it easier to compare each image. Download the images and use the left and right arrow keys to change between them.

#### Doom

Chocolate Doom

![doom-chocolate](https://user-images.githubusercontent.com/6550546/122809575-a02adb00-d311-11eb-9585-6ab6bceffbab.png)

Crispy Doom

![doom-crispy](https://user-images.githubusercontent.com/6550546/122809622-afaa2400-d311-11eb-8946-d7dea42a4105.png)

Russian Doom (incorrect)

![doom-russian](https://user-images.githubusercontent.com/6550546/122809651-bafd4f80-d311-11eb-9141-6f574ad521ac.png)

DSDA Doom

![doom-dsda](https://user-images.githubusercontent.com/6550546/122809672-c0f33080-d311-11eb-9c55-eca522e4453c.png)

#### Heretic

Chocolate Heretic

![heretic-chocolate](https://user-images.githubusercontent.com/6550546/122809698-cb152f00-d311-11eb-811c-17f9755f7ee3.png)

Crispy Heretic

![heretic-crispy](https://user-images.githubusercontent.com/6550546/122809727-d5372d80-d311-11eb-825e-29cae5fd5f71.png)

Russian Heretic (incorrect)

![heretic-russian](https://user-images.githubusercontent.com/6550546/122809753-dbc5a500-d311-11eb-8f8d-0ec7dd6b3deb.png)

DSDA Doom running Heretic

![heretic-dsda](https://user-images.githubusercontent.com/6550546/122809803-eda74800-d311-11eb-8da4-d0342012c28b.png)

#### Hexen

Chocolate Hexen

![hexen-chocolate](https://user-images.githubusercontent.com/6550546/122809837-f861dd00-d311-11eb-893f-b3cb21a08b9b.png)

Russian Hexen

![hexen-russian](https://user-images.githubusercontent.com/6550546/122809859-fe57be00-d311-11eb-9a68-6696bc8a22eb.png)

### Viewer

[view.zip](https://github.com/JNechaevsky/russian-doom/files/6688982/view.zip)

**Comment by JNechaevsky** [comment]
Hello. Speaking about Doom, could you please take a try to enable "Fake contrast" feature on the first page of "Gameplay features"? This must be the reason. 

RD is on the left part of screenshot, Crispy Doom is on the right:
![image](https://user-images.githubusercontent.com/21193394/122817470-9d63c200-d2e0-11eb-910d-ec27ecf64983.png)

**Comment by Mushman** [comment]
Oh wow. I just did some research and I had no idea that Fake Contrast was a Doom engine feature. Thanks a lot for pointing me in the right direction!

Maybe you should update Doom and Heretic so that they enable it by default. That way the games look correct on first launch.

Just out of curiosity though, does that mean Hexen disables Fake Contrast as part of its modifications to the engine? That would explain why it looks right with it left off, and how it looks too dark if I turn it on.

**Comment by JNechaevsky** [comment]
Oops, sorry for late reply!

> Maybe you should update Doom and Heretic so that they enable it by default. That way the games look correct on first launch.

Well, I'll have to explain. This is not a bug, it's a feature. :) I was thinking to make "everything off" on first launch, but later rejected this idea -- user will need to set-up a lot of things and enhancements to actually see them, while I definitely want to provide everything "from the box". Thus, I have left some will for myself to define what is "good" and what is "should be off by default".
Fake contrast was a necessary thing back in DOS era on 320x200 14" monitors, this way it was easier to see a walls with different angles I suppose. Nowadays, in modern monitors it does not looking very _proper_ in my opinion, that's why I have disabled it.

Another important thing is - the port itself is not about "vanilla", it's about enhancements. Many vanilla bugs have been fixed, but from another hand, this making game mechanics no longer 100% vanilla-like. However, I'm trying to preserve a full compatibility with vanilla IWAD demos, and there is a `-vanilla` command line parameter, which will return about 95% of vanilla behavior.

**Comment by JNechaevsky** [comment]
Forgot to mention - Heretic was also using fake contrast, it was removed only in Hexen (probably because of maps with fog). 
I would like to keep lighting mode "as is", it's established for a long time of project existing.

But anyways, thanks for your suggestion and your time!

**Comment by Mushman** [comment]
No problem. I do think Doom and Heretic look better with fake contrast enabled (the screenshot of Doom 2 Map 1's first room is a good example, the pillars have better shading). However I see you changed the default gamma in each game as well. In any case, I'm glad you give users the option to change the fake contrast setting, so that works for me. Great work with the project so far!
