### ISSUE TITLE
Two issues in Russian Hexen 4.1

### ISSUE THREAD

**Issue by ghost** [Russian-Doom/russian-doom#247]
...

**Comment by JNechaevsky** [comment]
Hello @collboi, thanks for your interest.

Yep, there is a confirmed, huge problem with MAP10, I have really screwed up some thing by trying to fix rare bug in Death Kings (https://github.com/JNechaevsky/russian-doom/issues/210). Now it should be fixed, but the only thing I simply can't say for sure - will saved games work properly after fix. On starting a new game, typing `VISIT10`, leaving map and going back again everything seems to be okay.

As about MAP22 issue - I can't reproduce it. Could you please double check on your side, is it happening on starting a new game and by loading saved game?

Here's a fixed versions, almost nothing changed since released 4.1:
[rus_hexen_pre_4.2-win64.zip](https://github.com/JNechaevsky/russian-doom/files/6728231/rus_hexen_pre_4.2-win64.zip)
[rus_hexen_pre_4.2-win32.zip](https://github.com/JNechaevsky/russian-doom/files/6728230/rus_hexen_pre_4.2-win32.zip)

**Comment by ghost** [comment]
...

**Comment by JNechaevsky** [comment]
Hooray! I'll leave this issue open until a proper updated release. Hopefully, it will come in upcoming weekend.
