### ISSUE TITLE
[HeXen] Corrupt save game: Segment [104] failed alignment check

### ISSUE THREAD

**Issue by valter12437** [Russian-Doom/russian-doom#254]
I'm getting this error every time I step on the teleporter to the Seven Portals. I'm using Windows 10, and my HEXEN.WAD is from the GOG version of the game.

**Comment by JNechaevsky** [comment]
Please make sure you are using latest RH version, which was released yesterday: https://github.com/JNechaevsky/russian-doom/releases/tag/hexen-4.2

**Comment by valter12437** [comment]
I am using the latest version. The bug still occurs depending on the folder where the files are placed. I'm guessing this might be a problem on my end now...

**Comment by JNechaevsky** [comment]
This can be important. Could you please provide more information about folders placement?

**Comment by valter12437** [comment]
This is the file path:

C:\Users\valte\Documents\Jogos\Source Ports\id Tech 1\russian-hexen-4.2-win64

The port works everywhere else but the "id Tech 1" folder for some reason. Renaming the folder didn't seem to do anything. Changing permissions also don't seem to do anything. Changed to and from "read only" and nothing. Other ports like "Russian DOOM" are working fine while in this folder. 

Furthermore, HeXen savegames are either deleted or corrupted as soon as they are created while the port is located in this folder.

**Comment by Dasperal** [comment]
I could not reproduce this error but I could reproduce the bug with "deleted" saves. The issue is in the length of the save path. Currently, Hexen uses a maximum of 100 chars for the full path to a save file. If the path is larger than 100 chars the save files won't be created.

You can use `-savepath <path>` command-line option to set a custom location for the save files.
