### ISSUE TITLE
Allow autoload PWADs in Heretic and Hexen

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#261]
Doom allows having up to 4 PWADs in autoload (global + game-specific) via .ini entries. This is useful e.g. for loading spritefixes and sound improvements while still being able to load another pwad externally. 

It would be great if Heretic and Hexen supported this feature as well. (I assume it's not like this yet since these games are still not on the same level as Doom coding-wise.)

**Comment by JNechaevsky** [comment]
It is already here, at least in Heretic (Hexen is planned, but only after Doom/Heretic updates), done via https://github.com/JNechaevsky/russian-doom/commit/c2a9b8acb746cc98632972a7572d2042ce53d2f1. It allows to load four PWADs globally, four for registered only (3 episodes) and four for retail only (5 episodes). Shareware is not present because shareware version should not allow to load any pwads with both autoloading and `-file` parameter. Here's an example:
```
autoload_global_pwad1         "sfxpure.wad"
autoload_global_pwad2         ""
autoload_global_pwad3         ""
autoload_global_pwad4         ""
autoload_registered_pwad1     ""
autoload_registered_pwad2     ""
autoload_registered_pwad3     ""
autoload_registered_pwad4     ""
autoload_retail_pwad1         ""
autoload_retail_pwad2         ""
autoload_retail_pwad3         ""
autoload_retail_pwad4         ""
```

Speaking about Heretic - it's now far, far better than currently released version. A **lots** of improvements was done, including stability, performance, features and mod compatibility (notably custom status bars and skies), and of course supreme 21:9 backgrounds by Nash Muhandes.

The only thing I can't say for sure is a release date. I hate to give an empty promises about release (usually it's "in upcoming weekend", but barely this was ever happening!), but also I hate to say "when it's done". It's polished, tested and working fine, but there are still some plans, so the best I can say is "please stay tuned". :/

I'll keep this issue for Hexen, there still a lot of work to do, but luckily, most of the improvements can come directly from Heretic.

**Comment by NightFright2k19** [comment]
Alright, that should already be good enough! I am using the official releases, so I guess I'll have to wait for the next Heretic update first.

**Comment by JNechaevsky** [comment]
All done! Released version of Heretic have this feature, massive Hexen update is still underway (but mostly finished). If you wish to check out, just take a try an autobuild from Artifacts section: https://github.com/JNechaevsky/russian-doom/actions/runs/1704124271#artifacts

**Comment by NightFright2k19** [comment]
Thanks a lot! Looking forward to the next release, then!
