### ISSUE TITLE
[Feature] Fullscreen HUD variant

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#262]
While it's nice to have options turning off specific parts of the HUD, it would be great to also have a neutral HUD with all the essential info, but aligned to the side of the screen to not obstruct viewing weapons.

Ideal would be [the HUD from PrBoom+](https://image.gcores.com/d9c89d20-30ea-4c82-8d5b-0ef8892439ff.png?x-oss-process=image/quality,q_90 ).

This could be added as yet another option if going beyond existing fullscreen options (before having no HUD at all).

**Comment by JNechaevsky** [comment]
Oh no, that's the thing I was always trying to avoid - custom HUDs. :)

Not because of complicacy, but because of there is no ideal solution, which everyone will like. I can't let myself to replicate any existing custom HUD, this is not a fair play, especially from PrBoom - this is a different port with different philosophy.

This will require making a completely custom HUD, which must looks nice be informative, but I don't have any thoughts about it for the moment. Heretic, for example, now able to show all possible info, but it's a three sorted features, not a screen size ([screenshot](https://user-images.githubusercontent.com/21193394/126532047-f3519a21-9569-413c-9d37-a9edaf902f63.png)).

I don't want to reject this idea, but better keep it for better time, when I will have a proper idea what should be done and how it should look.

**Comment by NightFright2k19** [comment]
Alternatively, it could be considered to take an approach similar to what we did with the [Fullscreen Statusbar Mod](https://i.imgur.com/9PyNAMX.png) for GZDoom. Cut the bar in half, move each half to one side of the screen, replace the "ARMS" panel with the mugshot and put the weapon numbers on top of it. It would free up a lot more screen space in the center.

I could imagine this here with the STBAR background completely transparent, but the "Ammo", "Health", "Armor" and ammo names still visible, mugshot without the black background, ARMS numbers on top. It could be another option, possibly inserted as a new last option before no HUD is shown any more. Zero information loss this way. [Here is a screenshot mockup](https://i.imgur.com/US2Ot7j.png) to illustrate the idea.

If it's also still too much effort, another idea could be to do at least the minimal approach and replace the ARMS display with the mugshot, so that you don't lose that iconic part of the statusbar.

**Comment by JNechaevsky** [comment]
Sorry, I totally forgot to reply here. Thanks for mockup! I'm sure this will be something and only one I'll come up with, but please, not now. It's already takes a couple of months of headache to polish RD to make it more stable and much faster in extreme rendering scenes. Just, please, give me some time to calmly release 5.0 version. :)

**Comment by JNechaevsky** [comment]
All done. Wider status bar is available in widescreen modes only as new screen sizes. Appearance is same to non-wide versions:

* Signs, player face
* Signs only
* No signs, just digits. 

![image](https://user-images.githubusercontent.com/21193394/130508659-52922324-dcc6-4452-8005-8f921793f16a.png)
![image](https://user-images.githubusercontent.com/21193394/130508675-2f3b8b59-4665-4634-8373-dac3ea13a9d4.png)

Honestly speaking, I was wrong by thinking that it will be looking wrong. Nope. It's not wrong, it's just unusuall and have it's usefulness. But for God's sake, let it be the last changes done to status bar. 🙂

@NightFright2k19 thank you for inspiring me to finally to do this!

**Comment by NightFright2k19** [comment]
Outstanding! Having the mugshot in the center is still a bit weird since it's EXACTLY where the weapon is drawn, and that's the area you normally want to be visible. Seems it can be hidden like before, though, so I guess it's as good as it can get. Thanks a lot for this!
