### ISSUE TITLE
Duplicate asset in doom-common.wad

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#270]
It appears as if the Russian version of the STBAR lump (RDSTBAR) is included in doom-common.wad twice. The first version (which is not used due to lump load order) seems to be better due to its better shadows for the ammo name letters and its properly centered "ARMOR" label. 

However: 
- First version has a green pixel on the right side (ammo overview panel)
- Second version seems to have a better "AMMO" label due to its second and fourth letter to be improved/fixed

I have taken the liberty of applying fixes for both issues to the first RDSTBAR version, including a widescreen variant based on the statusbar included with the Doom Unity release.

![RDSTBAR_fixed](https://user-images.githubusercontent.com/54737241/130018981-c2f2546f-c5c6-4d34-a1f6-1ea29ad7d6fb.png)
![RDSTBAR_fixed-wide](https://user-images.githubusercontent.com/54737241/130018983-39a9f4d7-b8e7-4984-99c4-7d2f0cb4cb11.png)

**Comment by JNechaevsky** [comment]
Oh, thank you for the efforts! Apperantly, I've already fixed lump duplication in upcoming version. Also, Unity assets gives only 16:9 wide version, in 21:9 there still be green borders (and since I have a 21:9 monitor, for me it's like needle in the eye).

I've also made a 21:9 stbars, friendly with 16:9, and even in two variants, but for some reason I don't want to include them. Really not sure why, maybe because it's too habit-breaking, maybe because states bar becomes "too bright". 

Honestly, I don't know how to proceed, i.e. include such status bars or not. Not everyone including myself may like such change.

![image](https://user-images.githubusercontent.com/21193394/130021715-de33cf31-eae9-49b1-aa33-47154f706f0e.png)

![image](https://user-images.githubusercontent.com/21193394/130021679-2f47e405-2ba4-42a6-b2a8-1deed0535164.png)

**Comment by NightFright2k19** [comment]
Nash also didn't include a Doom widescreen bar in his GZDoom assets. His argument for doing so was that other than for Heretic or Hexen, extending the graphics on both sides does not add anything new or interesting here, and it wouldn't be worth it just to make the "green bricks" disappear. 

I guess in the end you are better off using one of the fullscreen statusbar modes before wasting valuable screen space for ugly gray areas which don't serve any real purpose.

Maybe it makes more sense to rather update Heretic/Hexen statusbars with Nash's latest versions from his GZDoom widescreen assets. They look a bit nicer than the ones currently included, even though the differences are still not so huge in the end.

**Comment by JNechaevsky** [comment]
Guess I can only agree with Nash in this case. Another important thing: I don't want to include anything from Bethesda assets -  for me prohibition of John Romero to release any unused Doom content as well as removing original id Software logo from titlepics (now they are back) is nothing more than blasphemy. So no, thanks, not with such politics. 

Nash, in turn, did an amazing job with, just like he always did for community, so I gladly include his work.

Here is a PSD source of my 21:9 status bar: [STBAR.zip](https://github.com/JNechaevsky/russian-doom/files/7016606/STBAR.zip) (let it be here until I lose it). Really no idea what to do with further, maybe polish it a bit, or maybe just abandon. Or maybe release it as a separate .wad, which will be quite odd.

As about Heretic, well, current one isn't really bad for my taste, and it's been included for couple of years. Nash's version is also good, but I don't want to change some thing just because, don't get me wrong.

And as about Hexen, oh my, this one still requires a massive update. :) There is now new in-game menu as well as rendering improvement, but still no new Gameplay features. I thinking to start to working on it in the middle of September, just before five years anniversary release. Both Doom and Heretic are almost release ready, but I don't want to hurry.

**Comment by NightFright2k19** [comment]
Well, if I am looking at all the commits that have been made since the last releases, there's more than enough for a massive update.  But yeah, it's not a big loss if the statusbars remain as they are in this case. 

Thanks a lot for that STBAR source file, anyway. I am sure there are people who will still want this, even if it's just for the automap (where I think the statusbar is actually the most useless, but that's a different topic).

**Comment by JNechaevsky** [comment]
I have an idea - to do not reject this 21:9 stbar, I simply can put it into newly created Wiki (https://github.com/JNechaevsky/russian-doom/wiki), into section like a... "Useful WADs" and left a note in release changelog like: 
> It was supposed to be included, but later was rejected, but you still may use it as a separate wad file. It is also compatible with other source ports.

But some pixel-polishing is still needed, of course. Can be done right after wider st-bar implementation.
