### ISSUE TITLE
Questions about controls

### ISSUE THREAD

**Issue by vanfanel** [Russian-Doom/russian-doom#273]
Hi there @JNechaevsky 

I was thinking today that, back in the day, SPACE was the key to USE (open doors, etc) on Heretic originally. But setting SPACE to USE on the game menu, it does not work.
Using "e" or other letters work, but not SPACE.
Is this a bug or an intended behavior?

Also, is it possible to have axis in an Xbox360-like pad configured as analog so I can walk or run depending on the analog axis movement?

Thanks!

**Comment by JNechaevsky** [comment]
Hello @vanfanel! 👋
I have added `SPACE` as a default "use" action (along with `E`) into Doom and Heretic, in Hexen it's reserved for jumping. Initially it was intentional behavior, but I think it will be more comfortable for users, just like `MOUSE` / `LCtrl` combination for attack. But there is no `SPACE` binding problem on my side, so I can't reproduce it. Are you using Windows or some other OS?

As about XBox controller, probably @Dasperal can suggest something, I have only some kind of generic USB gamepad but never use it.

**Comment by vanfanel** [comment]
@JNechaevsky Thanks a lot for the SPACE default :)
I can bind it, but then it does not work.
I am using GNU/Linux on aarch64, and my SDL2 build currently runs on Wayland (no X11) so maybe it's an SDL2/Wayland problem if you can't reproduce it on SDL2/X11.

**Comment by Dasperal** [comment]
I think that the keypress event is lost somewhere in the processing because the space key is also bound to bk_jump. Currently when you bind a key to some action other binds of this key are not cleared. This is done because there are some actions that can't be bind by any way except through a config file which is not human readable.

As for gamepad support, it is currently in a "just works" state. Axes are analog but the value is not scaled so valid values result only in 0 and maximum movement speed.

I'll take care of it when the opportunity arises.

**Comment by vanfanel** [comment]
@Dasperal Thans a lot for the detailed answer :)
I will test analog mouse movement as soon as it's available!

**Comment by vanfanel** [comment]
@Dasperal I noticed that, in Russian-Hexen, SPACE is indeed hardcoded to JUMP!
Wouldn't it be possible to have the JUMP movement available on the control menu too? Currently, there's no way to un-bound jump, so that's why SPACE can't be configured for the USE action in both Hexen and Heretic...

**Comment by Dasperal** [comment]
Yeah, I totally forgot about jump binding.

Now it should be fixed along with other keybinding system problems.

**Comment by vanfanel** [comment]
@Dasperal Thanks a lot! Will test ASAP

**Comment by vanfanel** [comment]
@Dasperal Space as USE works perfectly now!

**Comment by Dasperal** [comment]
@vanfanel 
>Also, is it possible to have axis in an Xbox360-like pad configured as analog so I can walk or run depending on the analog axis movement?

Extended gamepad support was added.

I also changed the config file format. It is human-readable now.

**Comment by vanfanel** [comment]
@Dasperal This is incredible! Testing ASAP (not at home as of today...)
