### ISSUE TITLE
White pixels when loading custom map

### ISSUE THREAD

**Issue by somatzu** [Russian-Doom/russian-doom#276]
![Screenshot (6)](https://user-images.githubusercontent.com/15349552/134989027-64ffa3ee-a00d-4cdf-b18f-431fd408f6ba.png)

Hello, I get these white pixels when trying to load Back to Saturn X with Russian-Doom. Any advice? 

Also, love your port! It's the best out there in my opinion.

Thank you!

**Comment by JNechaevsky** [comment]
Hello @somatzu and thank you for kind words! 👋

Yeah, that's because of darken palette was created by hand from original Doom palette, and thus, it's not very friendly with custom palettes provided in mods. To avoid this problem, just increase gamma-correction level to "Standard gamma-correction OFF" and higher.

This problem can be solved enterely by using custom palette from the mods for generating darken one, but I still have no idea how to implement this.

**Comment by somatzu** [comment]
Spacibo bolshoi!

I will go ahead and close the issue then. This is really an amazing port and I wish you all best in your future efforts! I will be recommending it to everyone I know looking for the best Doom experience.

**Comment by JNechaevsky** [comment]
Na zdorovie :))) Thanks again and have a good game!
