### ISSUE TITLE
[Feature] Update max monster counter sooner

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#306]
When max monster counter changes (e.g. when an Archvile resurrects monsters), it only shows in the (optional) level stats when the max kill limit is reached. It would be helpful if the counter was immediately updated/adjusted.

Example: 
- 25/50 monsters killed when Archvile resurrects a monster
- Kills in level stats switch to 26/50. Better would be if it already was like: 26/50+1
- Counter continues until 49/50, and only when you reach 50, it shows 50/50+1 --> so you are still missing one kill

The "problem" is as long as you haven't reached the original limit, you don't see the ACTUAL amount of monsters you still have to kill, just the ones that were there originally. Maybe this is intended, but IMO it's not totally accurate and can be confusing.

**Comment by JNechaevsky** [comment]
Thanks @NightFright2k19, this is case is interesting to think about. AFAIK, some ports handled it differently, but I think I can handle it by my own. 

Some thoughts...

There is exactly one counter for kills - a `killcount`. It can be divided to a two counters: `killcount` and `extrakillcount`. First one should be incremented normally, if mobj have a `MF_COUNTKILL`, and next comes a difference: once mobj is resurrected by Archvile, `MF_COUNTKILL` should be removed and `MF_COUNTEXTRAKILL` should be set, and once resurrected monster is killed, it's not counted for common kills, just for extra. This way we can exactly count killed normally and resurrected monsters and show correct stats, at least in widget. Touching tally stats does not seems to be a right way to go, better just leave it as is.

Probably same logic should be applied to self-resurrected monsters in Nightmare / Ultra-Nightmare skill levels.

Cons? Yes, `extrakillcount` should be preserved in saved games, which will break compatibility with previous version of the port. But this is okay since it is already broken after map mark was written in saves.

**Comment by NightFright2k19** [comment]
With Lost Souls spawned from Pain Elementals it's the same thing btw, forgot to mention this case. In return, I dunno if it's a factor in Heretic at all due to the lack of resurrecting/spawning monsters.

There are some maps where monsters aren't counted until they enter the map. Just played one of these, noticed because I use a GZDoom widget which shows kills and suddenly the max amount increases when mobs are teleporting in. Quite annoying, actually...

**Comment by JNechaevsky** [comment]
If I remember correctly, starting from vanilla Doom 2 (v1.666 and higher) Lost Souls aren't counted with kill counter at all, since they can be spawned by Pain Elemental. RD emulates v1.9 behavior, and I believe better don't count them as extra kills, to keep vanilla behavior and don't make counter more complicated.

Honestly, I'm not familiar with modern GZDoom and simply have not idea how thing are going there.

**Comment by NightFright2k19** [comment]
You are as fast as lightning! Thank you kindly!

**Comment by JNechaevsky** [comment]
Thanks for inspiring me to finally do something about it!

I have changed tally screen logics as well, now it does not counting "extra kills". Otherwise stats will be confusing: HUD widget shows one, tally screen show another. Map30 will still be able to show > 100% kills because monsters are spawn "normally", i.e. not resurrecting/respawning.

Widget format is slightly changed as well to "kills + extra kills _(if > 0)_/ total kills". For example - there are two enemies on the map, Zombieman and Arch-vile. Zombieman was killed, then resurrected by Archie, then killed again, this leads to "1+1". Tally screen will show 50%.
![image](https://user-images.githubusercontent.com/21193394/152058793-a54b2f1f-9864-434d-9b41-fe27352beac8.png)

> I dunno if it's a factor in Heretic at all due to the lack of resurrecting/spawning monsters.

In common scenario - nope. However, there is a `-respawn` command line parameter, and Level Select menu also able to turn this feature on, so I'll have to take care about Heretic, too. Just not today, it's a bit late. :)

**Comment by NightFright2k19** [comment]
Yeah, that makes sense. Hadn't thought of MAP30, numbers can go crazy there. Good thinking!

**Comment by JNechaevsky** [comment]
And done for Heretic as well. Logics is absolutely same, `+N` for extra kills.
![изображение](https://user-images.githubusercontent.com/21193394/152111103-a32845a6-a6c3-4d89-afad-8ff1fcc6f1d2.png)

I've also fixed `TNTEM` cheat for Doom, which was not killing resurrected monsters after first use. It's same to Heretic's `MASSACRE`.
