### ISSUE TITLE
[Feature] Customizable level stats

### ISSUE THREAD

**Issue by NightFright2k19** [Russian-Doom/russian-doom#316]
1) It would be great if there was a way to adjust the optional level stats display (kills, items, secrets, skill). With "adjust" meaning: Being able to choose what you want to see.
For example, personally I only need kills and secrets, so there should be a way to turn off the other stats. Especially useful if you also want to use this outside of the automap (i.e. as a permanent display).

2) Additionally, it could be considered to be able to choose the location of the stats, i.e. top left/right or bottom left/right (without being hidden by any messages or icons, ofc).

3) Outside of the automap, icons could be used instead of text for the stats names (kills/items/secrets) to reduce consumed space on the screen.

**Comment by JNechaevsky** [comment]
I think it's about time to implement 2nd suggestion. Should be something like this...

![image](https://user-images.githubusercontent.com/21193394/202872646-9d5b7419-04b7-4cf8-97a7-e7c7f8ad4a38.png)

Other items like "Total level times", "Skill" and "Coords" are also can be placed there, but it will looks like a hamburger. But they are optional, and if user wants them, they are free to turn it on.

Coloring seems to be okay, but the code itself needs some polishing - it's a bit tricky to partially colorize KIS stats - technically it's not a one string, and I can't use fixed coords there because of counters can be different in length.

**Comment by JNechaevsky** [comment]
Final result with all available widgets:
![st_anim](https://user-images.githubusercontent.com/21193394/202900328-df56cdc1-7efc-43b1-99c2-c67899f9dd46.gif)
