### ISSUE TITLE
[BUG] International Doom 5.3 won't load wads previous versions could

### ISSUE THREAD

**Issue by cubebert-github** [Russian-Doom/russian-doom#353]
### International Doom version

International Doom 5.3

### What Operating System are you using?

Windows 10

### What Build variant of International Doom are you using?

x64 (amd64, x86_64, win64)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It's been a while since I've played International Doom, especially since I've been busy with getting my new computer set up. I downloaded the latest version of the source port and noticed a couple of things that weren't in the previous version, 5.2.1. First, I tried to start up Doom 2 with a mod called DBZDOOM2; I couldn't find it online and it came from a [compilation of Doom wads](https://www.doomworld.com/forum/topic/114671-%F0%9F%8D%A6-big-vanilla-doom-wad-pack-rev-16-may-24th-2022-maximum-doom-the-way-kid-did/), so I'll attach the mod to the bug report. When I used 5.3 to start a new game, I wasn't able to because the game would crash. 5.2.1 didn't have this issue and can be demonstrated by waiting for the first demo to start after booting up the game, as seen in the video below.

https://user-images.githubusercontent.com/24487663/173259990-5e31cbe3-ce54-42ed-95af-bc7a6a238c63.mp4

Next, I loaded up the same mod with [Hell Revealed 2](https://doomwiki.org/wiki/Hell_Revealed_II), and I got an error message stating that there were too many lumps to load. 5.2.1 didn't have this error, and played normally as expected.

![2022-06-12_170750](https://user-images.githubusercontent.com/24487663/173260102-25a8f298-9558-4e6f-b4b8-0c2386dd91a1.png)

Since it has been a while, I wanted to know if these were bugs introduced in 5.3 or if they were part of a design choice made for 
this version. Here are the wads to load for reproducing the crashes.

[DBZDOOM2.zip](https://github.com/JNechaevsky/inter-doom/files/8887094/DBZDOOM2.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load up the attached wad and deh files to International Doom 5.2.1 and start a new game. 
2. Next, load Hell Revealed 2 and the same attached files to International Doom 5.2.1.
3. Then, load only the same attached files to International Doom 5.3 and try to start a new game.
4. Finally, load HR2 and the files to International Doom 5.3.

**Comment by Dasperal** [comment]
It crushes because of the new statusbar drawing code.

In the first case with only DBZDOOM2, the reason is that this mod increases maximum of bullets to 1000. When this value is rendered
https://github.com/JNechaevsky/inter-doom/blob/564905cba3b64ac15be11369f1ceae52aa6790ff/src/doom/st_bar.c#L1396
it results in accessing eleventh element of the `FontSNumbersY` array, but `FontSNumbersY` has only ten elements, so a garbage value gets passed to `V_DrawPatch` resulting in SIGSEGV.

In the second case with DBZDOOM2 and Hell Revealed 2, the reason is here
https://github.com/JNechaevsky/inter-doom/blob/564905cba3b64ac15be11369f1ceae52aa6790ff/src/doom/st_bar.c#L2008-L2012
The `FontSNumbersY` array is populated with a sequence of 10 lumps starting from `STYSNUM0` inclusively. Hell Revealed 2 overwrites whole `STYSNUM` font and DBZDOOM2 overwrites some of it's lumps including `STYSNUM0`. It somehow result in `STYSNUM0` occurring in less than 10 lumps from the end of the lumps list, when DBZDOOM2 is loaded after Hell Revealed 2.

**Comment by JNechaevsky** [comment]
Thanks @cubebert-github, thanks @Dasperal

Oh my, having more than 999 ammo is totally unconventional. 😳 
But no problem, if it's working in vanilla Doom, then it should work here. Figured it out, there are exactly two problems.

First one, as Dasperal have mentioned, with font drawing functions. They simply can't draw values above `999`, and this can be easily fixed by following condition:
```
if (value > 999)
    value = 999;
```

Second one is more complicated. In short words, Raven Software digits loading routine, which used now, is expecting proper lump ordering along with all patches for digits loading (from `STYSNUM0` to `STYSNUM9`). DBZDOOM2.WAD have a different `STYSNUM` lump ordering, which is leading to incorrect loading and drawing some of them as a trash ([screenshot](https://user-images.githubusercontent.com/21193394/173298081-ea213784-9e9d-44b8-ab66-1bdfacd0657f.png)). 

Simplest way to fix it is just fall back to Doom digits loading routine, it is not bad at all. I see there a tiny potential for optimizing as well.

Finally, to make a friendship between DBZDOOM2 and HR2, I belive this order should be used:
`inter-doom.exe -file hr2final.wad DOOMZ.WAD -deh DOOM2Z.DEH`
This should make looking everything okay ([screenshot](https://user-images.githubusercontent.com/21193394/173300721-56729575-29bb-4205-a9c1-428caa770e07.png)).

I'll commit changes shortly.

**Comment by JNechaevsky** [comment]
I have updated executables in Doom released archives, download links are same. They also includes better config migration code by Dasperal. Not very good move, but it's better than for new version to be released.

Thanks again!
