### ISSUE TITLE
[Feature] Less Reliance on Bloat/"Lite" Version?

### ISSUE THREAD

**Issue by OpenRift412** [Russian-Doom/russian-doom#386]
### Is your feature request related to a problem? Please describe.

Something I've always been a bit critical of when it comes to this port is that out of the box it comes with a lot of extra bloat. Widescreen assets are one thing, but using the minor sprite fixes really should be user-choice, not coming pre-packaged. I go to the base directory to remove it, but then find that International Doom REQUIRES that you have doom-extra.wad in order for it to even launch. There's a lot of WADs that this port seems to rely on when it doesn't really need to, and it kind of hurts its versatility and portability as a port.

### Describe the solution you'd like

Have it so the port doesn't require all the extra WADs and their content lumps in order to run properly, just doom-common.wad.

### Describe alternatives you've considered

Make a "Lite" version of the port which only comes with doom-common.wad, among some other simplification of features for a cleaner, more light-weight experience.

**Comment by Dasperal** [comment]
Wads in the `base` directory is port's internal resources (like `gzdoom.pk3`). Those resources are required for a whole port or some of its features to function. They are not meant to be touched by the user.

The `doom-extra.wad` is loaded only if no `FREEDOOM` nor `FREEDM` lump is present.

**Comment by JNechaevsky** [comment]
Indeed. More of that, having "full/lite" version will require to maintain four releases in total (full/light for x86 and x64). Lite version will not give any performance benefits aside from port distro size, since extra resources are loaded only when they are called and needed.

I prefer to have to keep things simple, w/o necessity to download anything separately and have everything from the box. Yes, distro size is quite big comparing to other projects, but on nowadays HDD/SSD capacity this is not the size that matters.
