### ISSUE TITLE
[Feature] Disable Ultra-Nightmare when Vanilla-Strict Mode is Enabled

### ISSUE THREAD

**Issue by OpenRift412** [Russian-Doom/russian-doom#389]
### Is your feature request related to a problem? Please describe.

It doesn't really make much sense that Ultra-Nightmare would be an option when vanilla-strict mode is enabled, since you can't really record a vanilla demo of the Ultra-Nightmare mode anyway.

### Describe the solution you'd like

If Vanilla-Strict Mode is enabled, hide Ultra-Nightmare from the difficulty selection as well as use the original graphic for regular Nightmare difficulty instead of the re-punctuated version.

### Describe alternatives you've considered

I've tried removing M_NMARE and M_UNMARE from doom-common.wad, but I can't even access the difficulty screen without crashing if I do that.

**Comment by JNechaevsky** [comment]
"Strict mode" is only about game mechanics, not menu layout or design. I can't just hide it, since there are users who like sixth skill level and found it entertaining, and this menu item is hiding automatically if custom `M_ROUGH` is existing in loaded PWAD for providing some reasonable compatibility.

Removing `M_UNMARE` is a no-go, this way skill menu will refer to nonexisting patch, and this will lead to a crash. Instead, if you want to hide it permanently, just replace it with dummy empty 1x1 patch like `TNT1A0`, which is also present in doom-common.wad.
