### ISSUE TITLE
Viruses Detected In Latest Version Of Port

### ISSUE THREAD

**Issue by MrRumbleRoses** [Russian-Doom/russian-doom#395]
has anyone by chance pointed out that the latest version of International Doom "contains a virus"? cause each time i try & download the port to update it, it always fails because of a virus detected

**Comment by fabiangreffrath** [comment]
Apparently, virus scanner have become so utterly stupid that they consider anything not compiled with MSVC to be a virus. Add some functions to read or set a code page or to read from stdin and your are a serious suspect. 🤦

**Comment by rfomin** [comment]
> Apparently, virus scanner have become so utterly stupid that they consider anything not compiled with MSVC to be a virus.

Virus scanners also don't like our 32-bit MSVC build of Woof too. I guess the `.com` launcher is not a good idea after all.

**Comment by MrRumbleRoses** [comment]
yikes. sounds crazy for sure

**Comment by Dasperal** [comment]
It is false positive and comes from "﻿inter-doom.com﻿"﻿ file. If you don't use CLI, you can delete it.

Q: Why does "﻿inter-doom.com﻿"﻿ exists?
A: Because of Windows's stupid application types. App can either be Console or GUI. Only Console app can properly attach to parent terminal (cmd, PowerShell, etc.), but always creates new console window if there is no parent one. The first approach was to make Inter Doom a console app and close the console window when it is not needed, but @JNechaevsky didn't like the blinking window, so we decided to go with the console wrapper. The ".com" extension have priority over the ".exe" if no extension specified in the command line, like "inter-doom --help".

At the beginning it had only 3/72 false positives and I managed to fix them for x64 builds by removing some function calls that read input stream code page and console mode. Now then it is 32/64 false positives, I think that we need to come up with more sophisticated launcher on Windows.

**Comment by rfomin** [comment]
> At the beginning it had only 3/72 false positives and I managed to fix them for x64 builds by removing some function calls that read input stream code page and console mode. Now then it is 32/64 false positives, I think that we need to come up with more sophisticated launcher on Windows.

I think we can provide an alternative build with console support. Every other solution seems to have problems.

**Comment by MrRumbleRoses** [comment]
as long as it works for 32 bit computers, and i don't have to get virus detected BS. i'm down for whatever can work

**Comment by Dasperal** [comment]
Almost everything was fixed, but I can't guarantee that it won't come up again.
And it's a very annoying work to try to bypass the stupid heuristic AI of antivirus. I don't want to do it ever again.
If your antivirus still detects viruses, report it to your antivirus maintainers as false positive.
