### ISSUE TITLE
Reverse port to English?

### ISSUE THREAD

**Issue by Danfun64** [Russian-Doom/russian-doom#42]
Aside from translating to Russian, it seems this port has some exclusive enhancements: mainly for Heretic, Hexen, and DOS Doom. Although the English speaking Doom community isn't your target audience, it would be nice if we could get the non Russian translated related changes.

At the very least, could you make the original English text and graphics as an option, even if not the default one?

**Comment by JNechaevsky** [comment]
Hello @Danfun64, and thank you for positive feedback!

I was thinking about adding an English as optional language into setup executable about half of year ago, but decided to don't this. In general, there are a couple of reasons why it shouldn't be done, but also a couple of why it should be. Here they are:

**No:**

- The project is primary posed as a translation, and having an English language may be odd.
- In fact, I don't have support for Russian characters - all the characters are "redrawn" English characters, placed respective to Russian keyboard. This is not very nice in technical meanings, but making many things much easier and player will never need to care about his keyboard character layout, especially if keyboard have some non-standard chars. Thus, all translated texts are placed right in the executable, exception - Freedoom.
- Even if I restore proper support for English language, my project is still not very friendly with heavy mods and total conversion. The reason of that - I have some unique features thats are resource-dependend, and that's why I'm mostly care only about vanilla game series.

**Yes:**

- Translation part is done, my primary interest now is having a good picture, optional features and preserve original game feeling. 
- Having an optional English language is a huge step forward to anyone who is not speaking English. I only can imagine how confusing Russian texts are looking for them. :)
- Also, it's a good ethics, since even Russian players may preffer to see traditional English texts in the games. This is purely a question of habits, but anyway.
- And also, having an English language is a good thing in terms of internatiolization. Needles to say that English language is a worldwide known.
- English language may be considered as an original game content. Just like internal demos, which I'm trying to preserve without desyncs by any costs.
- Finally, having an English language may be a huge step forward for mods compatibility. Well, at least for some of them.

But there is one more thing - implementation's headache. There are could be few approaches:

1. Having in-game option, which will change the language "on fly", ideally without restarting the game. I believe it's a most proper way to go, but really not sure I'll handle it.
2. Having a command line parameter, line `-english`. Probably much easier, but I'm trying to force anyone to use command line as small as possible. Most of my auditory is using Windows and may be not very friendly with command line and/or batch files.
3. Option in Setup executable.
4. Making an separate branch - but nope, this is definitely out of scope.

That's it. In more short words: I don't know how to properly do this, but neither I want to reject this idea. :)

**Comment by jeffdoggett** [comment]
Another option is to implement the LANGUAGE lump, which is basically a DeHackEd reader for strings.
https://zdoom.org/wiki/LANGUAGE
There's a default English file somewhere, cannot remember offhand where I saw it.

**Comment by JNechaevsky** [comment]
Thanks @jeffdoggett, this sounds like a good plan. Not sure I can implement whole `LANGUAGE` lump specifics, but probably can do something about moving translated stings into separate lump and load it similarly to Dehacked lump.

This still will not make this project supreme compatible with mods, but at least will bring some nominal ability for non-Russian speakers who simply want to check out port's features.

Still not sure how English language will be activated. Ideally it should be an item right in game menu, but string replacement "on fly" does not seems to be possible. Using a `-english` command line parameter seems to be most painless approach, but really not nice.

Another possible way is making an option in Setup executable, but this probably is also not very good - some people may simply start game executable without any care about configuration (controls and other stuff, which is already tweaked by default).

**Comment by Danfun64** [comment]
Maybe you should do the reverse? Restore all the English strings where they're supposed to go, and then put all the Russian text in the hypothetical LANGUAGE lump?

**Comment by JNechaevsky** [comment]
Yeah, this is exactly I was thinking about :) Otherwise it will be strange to put original English content, which is always available "as is" in the game, as separate files.

**Comment by JNechaevsky** [comment]
I'm starting to get the idea. It's pretty raw at the moment, but some initials are formed. So, the folder "russian" should be renamed to "base" (just like in other id's games), as well as it's contents:



file | contents
-----| --------
doom-beta.wad | Press beta stuff | 
doom-beta-russian.wad | Press beta translation |
doom-common.wad            | Additional Doom stuff, like brightmaps, palette and some additional GFX like "Ultra-Nightmare!" and "Quick Loading" |
doom-common-russian.wad    | Translated graphical text elements |
doom-doom1-russian.wad     | Doom 1 translation stuff |
doom-doom1-skies.wad       | Doom 1 taller skies for mlook |
doom-doom2-russian.wad     | Doom 2 translation stuff |
doom-doom2-skies.wad       | Doom 2 taller skies for mlook |
doom-master-russian.wad    | Master Levels translation stuff |
doom-nerve.wad             | No Rest for the Living translation stuff |
doom-plutonia-russian.wad  | Plutonia translation stuff |
doom-plutonia-skies.wad    | Plutonia taller skies for mlook |
doom-tnt-russian.wad       | TNT translation stuff |
doom-tnt-skies.wad         | TNT taller skies for mlook |
freedoom-common.wad        | Common stuff for Freedoom, independent from Doom's common | 
freedoom-russian.wad       | Freedoom translation stuff |
freedoom-dm-russian.wad    | FreeDM translation stuff |
heretic-common.wad         | Additional Heretic stuff, like brightmaps, palette and etc. |
heretic-common-russian.wad | Translated graphical text elements |
heretic-demo-russian.wad   | Translated demo-specific elements |
heretic-registered-russian.wad | Translated registered-specific elements |
heretic-retail-russian.wad | Translated retail-specific elements |
hexen-common-russian.wad   | Translated graphical text elements |
hexen-beyond-russian.wad   | Translated beyond-specific elements |
hexen-dd-russian.wad       | Translated DKoDC-specific elements |
hexen-demo-russian.wad     | Translated demo-specific elements |

Now about the code. Almost all game texts are macro-defined, so it will be better to follow the suite and define Russian strings like additional `PRESSYN_RUS`, while keeping English as original `PRESSYN`. Not sure how a perfectly proper choose here, but something like this could work:

```
M_StartMessage(DEH_String(english_language ?
                          ENDGAME : ENDGAME_RUS),
                          M_EndGameResponse,true);
```

Ideally, variable `english_language` should be placed in the first place inside config files. Even this way not everything that simple - for example, level lames are placed inside *chars and etc, but I think I can handle it. Hopefully.

And most important - language switching. I think the only good approach is to a choose inside Setup executable when it's just started, variable `english_language` will do the rest.

There will be exactly one aesthetic problem with all of this - save game titles. Saving them in English, and loading game in Russian will make their in-game names like unreadable abracadabra. That's because, in fact, Russian chars are still entirely replaced English ones. Not sure it's a _real_ problem, but I still can make a different extensions for different languages (.rsg / .esg).

It's a big, but not impossible job, and it should be done. The port itself still will not be very friendly with total conversions / mods because of some my cool additional assets, though, but at least some non-russian speakers will be happy to check out Press Beta and upcoming Atari Jaguar stuff.

**Comment by fabiangreffrath** [comment]
You could leave all strings in english and decide whether to apply a dehacked patch replacing them all with Russian pendants or not based on the variable choice.

**Comment by fabiangreffrath** [comment]
The same could be done with your translated menu entries, help pages, etc. Just put them into a PWDA together with a BEX patch replacing all English strings and only load this file if Russian translation is requested.

**Comment by JNechaevsky** [comment]
Wouldn't you like to see a vanilla Signed Crispy HUD? :stuck_out_tongue_winking_eye:

![](http://priscree.ru/img/a1dc5035791b33.png)

`DEHACKED` lump could be extremely helpful, needles to say, but it will not work with Hexen. I.e., it could work if some magic will done. I think I'll stuck with couple of `english_language ?` conditions, it's not looking as awful as I was thinking.

PWad structure is formed and understood, so now it's just a matter of time.

**Comment by JNechaevsky** [comment]
P.S. At the moment, I have exactly one question: how should I correctly say "I'm filled with nightmare" in old English? It's a new skill level in Heretic. Could it be a... "Thee filled with nightmare"?

**Comment by fabiangreffrath** [comment]
Saturated?  Enriched?

**Comment by JNechaevsky** [comment]
Probably "fulfilled", it's close to Russian meaning that I was trying to use. Oh well, this will be a headache of another day. Just got D1/D2/TNT/Plutonia working fine. I totally forgot that Press Beta was not simply translated, it was recreated as Russian only, so I was forced to make some GFX on English.

Some cool screenshots for today, but there is still a lot of work do.

- http://priscree.ru/img/8586b0a3dea53f.png
- http://priscree.ru/img/73d02361ee1712.png
- http://priscree.ru/img/73d020ca3c1d56.png

It's a quite an interesting feeling: the project feels same, but looks different. Hard to explain, but for some reason, I'm totally okay with English language, so I think I'm on right track.

**Comment by JNechaevsky** [comment]
Thee now know how to speakest Englishe againeth! Ye!

![untitled-1](https://user-images.githubusercontent.com/21193394/41559526-f06d6510-734c-11e8-8e9a-b33618955303.png)

Here I would like to deeply thank @jmtd for this variant of my "Koshmarom ispolnen ya" as well as @chungy for a link to the [article](http://tvtropes.org/g00/pmwiki/pmwiki.php/Main/YeOldeButcheredeEnglishe?i10c.encReferrer=&i10c.ua=1) about wrong "old English". It was a definitely new knowledge for me!

**Comment by JNechaevsky** [comment]
Cool! It takes two years to make all three games looking as I was dreamed, and it takes exactly seven days to implement back English language. Well, at least Plutonia 2 and Eternal Doom now working fine, without any graphical inaccuracies in English, while Russian still not very modding friendly (and never will be by obvious reasons).

The language can be easily switched in config file (`english_language`, `1` = English, `0` = Russian), but the real problem in just one small thing - I'm totally not lucky with implementing this switching in the Setup executable. Something not right in mode.c, language variable is not being binded in game selection window. Later hovewer, in main menu and deeper it's reading fine... Really no idea what to do next.

Switching prototype:

![default](https://user-images.githubusercontent.com/21193394/41821609-2975732c-77ec-11e8-9a47-8a83e96ec2e3.png)

**Comment by JNechaevsky** [comment]
Well, it's done. All the games, as well as Setup executable now have English and Russian language. For now, language can be changed to English in config files (by setting `english_language` to `1`), and in Setup's Main Menu (by pressing F4, or by clicking mouse button to the language string).

I hope no one will be sad by the fact that Russian will remain as default.

![](http://priscree.ru/img/1d21c0558f0e42.gif)

There is some polishing and pixel-perfection work to do English Setup, and most of `fprintf`'s are still in Russian. Not sure I will do something about prints, since my primary target is Windows, where player will never see that strings, but ideally, all `I_Error` messages should also have Russian and English languages.

Finally, I would like to thank @fragglet for recommendations regarding Setup executable, as well as for making such a great thing like TextScreen!

**Comment by JNechaevsky** [comment]
Well, this long way seems to be done. I have checked everything I could, and all seems to be fine. Next release will have support for both languages, switching will be available by setting `english_language` to `1` in config files (oops, they are .ini now), as well as is Setup executable by pressing F4 in main window (don't forget to save changes before exit).

Guess I can close this ticket now. Thanks @Danfun64 again, as well as everyone else.
