### ISSUE TITLE
[Idea] Apply only half of weapon bobbing amplitude for walking player

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#82]
Reduce bobbing aplitude by 2 (or less) while player is walking. Should be something like this:

**p_user.c @@ void P_CalcHeight**
```
player->bob >>= player_is_running ? 2 : 3;
```

**Comment by JNechaevsky** [comment]
Kinda working, looking pretty neat and most important - frames are interpolated while changing normal/reduced bobbing. But something not right, it's not working while holding `SHIFT` and diagonal movement (`W` + `A` or `D`). I need another solution rather than this:

```
    if (player&&(unsigned)((player->mo->state - states) - S_PLAY_RUN1) < 4)
    player->bob >>= 3;
    else    
    player->bob >>= 2;
```

Something must be done for catching only `RUN` button.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, may I annoy you for a second? Is it possible to use your code `boolean speedkeydown (void)` for this condition? Something like:

```
    if speedkeydown (void)
    {
        player->bob >>= 3;
    }
    else
    {
        player->bob >>= 2;
    }
```
I.e., how I should write it properly? But it could not work perfectly - with this approach it is possible to don't have an interpolation between HUD weapon placement while changing running/walking mode. And by the way, may this idea be somehow interesting for Crispy?

**Comment by fabiangreffrath** [comment]
What if you have auto-run enabled? What if you have assigned "run" to a mouse button?

Instead of checking for a specific key being pressed, I would rather check the player's momentum, e.g. here:
https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/g_game.c#L706

>  And by the way, may this idea be somehow interesting for Crispy?

As you probably know, the `player->bob` value is tightly connected to weapon bobbing, and since the weapon bobbing's y-value determines the time it takes to change between weapons, this must be considered demo-critical.  So, unless there is a safe approach presented somewhere for safely modifying this value, I'd rather decline. But thanks for asking!

**Comment by JNechaevsky** [comment]
Thank you! I've totally forgot about connection, yeah... Experimenting with `MAXPLMOVE` seems to be interesting, guess I can handle some specific conditions. Finally I've got a one-week confirmed vacation (first one for all this year, still can't believe!), so I will be able to dig into the code more deeply.  :smiley:
